# Basic Python

## 1. Split this string

In [102]:
s = "Hi there Sam!"
t=s.split()
print(t)
for i in range(len(t)):
  print(t[i])

['Hi', 'there', 'Sam!']
Hi
there
Sam!


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [7]:
planet = "Earth"
diameter = 12742
text="The diameter of {p} is {d} kilometers".format(p=planet,d=diameter);
text

'The diameter of Earth is 12742 kilometers'

## 3. In this nest dictionary grab the word "hello"

In [126]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d['k1'][3]["tricky"][3]["target"][3]

'hello'

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [39]:
ar=np.zeros(10)
#this is 10 zero array
ar
#and this 10 five array
ar+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [37]:
arrn=[]
n=18
while(n<34):
   n=n+2
   arrn.append(n)
arrn

[20, 22, 24, 26, 28, 30, 32, 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [45]:
#import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [49]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [56]:
data=[["Apple","furit"],["Tiger","Animal"],["Honey bee","Insect"]]
df=pd.DataFrame(data,columns=["Object","Type"])
print(df)

      Object    Type
0      Apple   furit
1      Tiger  Animal
2  Honey bee  Insect


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [ ]:
#I complete the date system for entaier Year.
m=1
month=["Jan","Feb","March","April","May","Jun","July","Aug","Sep","Oct","Nov","Dec"]
while(m<=12):
  text="The Month is {mon}".format(mon=month[m-1])
  print(text)
  if(m%2==1):
      for i in range(1,32):
        print(i)
  else:
    if(m==2):
      for i in range(1,29):
         print(i)
    else:
      for i in range(1,31):
        print(i)
  m=m+1;

   



## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [87]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
a2=np.array(lists)
df2=pd.DataFrame(a2)
df2

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24